spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15m
    refreshTokenExpiration: 604800 #7d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:3000/