spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true
websiteUrl: http://localhost:3000/