spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 #2h
    refreshTokenExpiration: 604800 #7d
stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    websiteUrl: http://localhost:3000/